version: "3"

networks:
  app:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    networks:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/src/

  php-fpm:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    networks:
      - app
    volumes:
      - .:/src
    ports:
      - "22:22"

  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=qwerty
    networks:
      - app
